server:
  port: 8000
contextPath: /

security:
  oauth2:
    client:
      clientId: grp-web-portal
      clientSecret: 123456
      accessTokenUri: http://inv.grp.gov.bd:8011/auth-service/sec/master/authentication/v1/login
      #userAuthorizationUri: https://github.com/login/oauth/authorize
      #clientAuthenticationScheme: form
    resource:
      #userInfoUri: https://api.github.com/user
