server:
  port: 9080
spring:
   application:
     name: Budget-Configuration
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         jdbc:
           lob:
             non_contextual_creation: true
     hibernate:
       ddl-auto: create
   datasource:
     url: jdbc:postgresql://localhost:5432/budget
     username: postgres
     password: password
     initialization-mode: always
     platform: postgres