server:
    port: 8888
  
spring:
    cloud:
      config:
        enabled: false
        server:
          git:
            uri: file:///C:/users/streamstech/config-repo
security:
  basic:
    enabled: false
  user:
    name: abirkhan04
    password: none