server:
    port: 8888
  
spring:
    cloud:
      config:
        enabled: false
        server:
          git:
            uri: https://github.com/abirkhan04/config-repo.git
security:
  basic:
    enabled: false
  user:
    name: abirkhan04
    password: none