package com.javaworm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-15T13:19:32.316+06:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://javaworm.com/", name = "CodeFirstService")
@XmlSeeAlso({ObjectFactory.class})
public interface CodeFirstService {

    @WebMethod
    @RequestWrapper(localName = "showPersonDetail", targetNamespace = "http://javaworm.com/", className = "com.javaworm.ShowPersonDetail")
    @ResponseWrapper(localName = "showPersonDetailResponse", targetNamespace = "http://javaworm.com/", className = "com.javaworm.ShowPersonDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String showPersonDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );
}
