package com.javaworm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-04-15T14:52:56.839+06:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://javaworm.com/", name = "SimpleServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SimpleServicePortType {

    @WebMethod
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://javaworm.com/", className = "com.javaworm.AddNumbers")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://javaworm.com/", className = "com.javaworm.AddNumbersResponse")
    @WebResult(name = "return", targetNamespace = "http://javaworm.com/")
    public java.lang.String addNumbers(
        @WebParam(name = "arg0", targetNamespace = "http://javaworm.com/")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "http://javaworm.com/")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "showPersonDetail", targetNamespace = "http://javaworm.com/", className = "com.javaworm.ShowPersonDetail")
    @ResponseWrapper(localName = "showPersonDetailResponse", targetNamespace = "http://javaworm.com/", className = "com.javaworm.ShowPersonDetailResponse")
    @WebResult(name = "return", targetNamespace = "http://javaworm.com/")
    public java.lang.String showPersonDetail(
        @WebParam(name = "arg0", targetNamespace = "http://javaworm.com/")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://javaworm.com/")
        java.lang.Integer arg1
    );
}
