server: 
  port: 8080
spring:
  datasource: 
    url: jdbc:mariadb://localhost/kotlin
    username: root
    password:  
    driverClassName: org.mariadb.jdbc.Driver
    dbcp2: 
    validation-query: SELECT 1
    continue-on-error: false
    initialize: true
    data: classpath:data.sql
  jpa: 
    properties: 
      hibernate: 
        enable_lazy_load_no_trans: true
    hibernate: 
      ddl-auto: update
      naming: 
        strategy: org.hibernate.cfg.ImprovedNamingStrategy 
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect